name: Test Screener Scraper

on:
  workflow_dispatch:  # Manual run

jobs:
  test-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run scraper test (3 pages)
        run: |
          echo "Starting test scrape..."
          python test_scrape.py
          echo "Tickers file content:"
          cat tickers.csv
